name: CI/CD Staging Environtment
on:
  push:
    branches:
      - "staging"

env:
  REGISTRY_NAME: kodinganku.azurecr.io
  KUBE_NAMESPACE: resto-backend
  APP_NAME: azure-resto-backend-staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: staging
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set Up Docker BuildX
        uses: docker/setup-buildx-action@v1
      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ secrets.CRAZURE_USERNAME }}
          password: ${{ secrets.CRAZURE_TOKEN }}
      - name: Set Up Environtment to Staging
        uses: canastro/copy-file-action@master
        with:
          source: ".env.staging"
          target: ".env"
      - name: Check version last commit
        run: echo ${ GITHUB_SHA }
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REGISTRY_NAME }}/resto-backend:${ GITHUB_SHA }
          context: .
          file: ./Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy to kubernetes cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image --record deployment/${{ env.APP_NAME }} -n ${{ env.KUBE_NAMESPACE }} resto-backend-container=${{ env.REGISTRY_NAME }}/resto-backend:${ GITHUB_SHA }
      - name: Verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: rollout status deployment/${{ env.APP_NAME }} -n ${{ env.KUBE_NAMESPACE }}
