name: building-Image
on:
  push:
    branches:
      - "staging"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set Up Docker BuildX
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Up Environtment to Staging
        uses: canastro/copy-file-action@master
        with:
          source: ".env.staging"
          target: ".env"
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: feriva22/resto-backend:staging
          context: .
          file: ./Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
